### ISSUE TITLE
Fatal error after extreme delay on display individuals

### ISSUE THREAD

**Issue by TheDutchJewel** [JustCarmen/webtrees-fancy-treeview#144]
I love the new ability to add name tags as described at [this forum topic](https://www.webtrees.net/index.php/forum/4-customising/38778-tagging-available-in-webtrees#104476). I am using two of them: one for births with sources, and one for deaths with sources.

But there is a problem: In my family tree of about 70,000 persons, displaying persons higher in the tree is getting slower and slower: about 54 seconds instead of 1.
And sometimes I get the a message about a fatal error:

`Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 141112808 bytes) in D:\xampp\htdocs\webtrees\app\View.php on line 185`

This I modified by increasing the `memory_limit` in `php.ini` from 512M to 10G. But then I get the following error message:
```
RuntimeException: View file not found: D:\xampp\htdocs\webtrees\modules_v4\jc-fancy-treeview/resources/views/block.phtml in D:\xampp\htdocs\webtrees\app\View.php:260
Stack trace:
#0 D:\xampp\htdocs\webtrees\app\View.php(183): Fisharebest\Webtrees\View->getFilenameForView('block')
#1 D:\xampp\htdocs\webtrees\app\View.php(278): Fisharebest\Webtrees\View->render()
#2 D:\xampp\htdocs\webtrees\app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make('_jc-fancy-treev...', Array)
#3 D:\xampp\htdocs\webtrees\modules_v4\jc-fancy-treeview\FancyTreeviewModule.php(880): view('_jc-fancy-treev...', Array)
#4 D:\xampp\htdocs\webtrees\modules_v4\jc-fancy-treeview\FancyTreeviewModule.php(783): JustCarmen\Webtrees\Module\FancyTreeview\FancyTreeviewModule->printGeneration()
#5 D:\xampp\htdocs\webtrees\modules_v4\jc-fancy-treeview\FancyTreeviewModule.php(631): JustCarmen\Webtrees\Module\FancyTreeview\FancyTreeviewModule->printAncestorsPage('I1310', 1, 9)
#6 D:\xampp\htdocs\webtrees\resources\views\individual-page-tabs.phtml(29): JustCarmen\Webtrees\Module\FancyTreeview\FancyTreeviewModule->getTabContent(Object(Cissee\WebtreesExt\IndividualExt))
#7 D:\xampp\htdocs\webtrees\app\View.php(183): include('D:\\xampp\\htdocs...')
#8 D:\xampp\htdocs\webtrees\app\View.php(278): Fisharebest\Webtrees\View->render()
#9 D:\xampp\htdocs\webtrees\app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make('individual-page...', Array)
#10 D:\xampp\htdocs\webtrees\modules_v4\vesta_classic_look_and_feel\resources\views\individual-page.phtml(54): view('individual-page...', Array)
#11 D:\xampp\htdocs\webtrees\app\View.php(183): include('D:\\xampp\\htdocs...')
#12 D:\xampp\htdocs\webtrees\app\View.php(278): Fisharebest\Webtrees\View->render()
#13 D:\xampp\htdocs\webtrees\app\Helpers\functions.php(145): Fisharebest\Webtrees\View::make('individual-page', Array)
#14 D:\xampp\htdocs\webtrees\app\Http\ViewResponseTrait.php(50): view('individual-page', Array)
#15 D:\xampp\htdocs\webtrees\app\Http\RequestHandlers\IndividualPage.php(124): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->viewResponse('individual-page', Array)
#16 D:\xampp\htdocs\webtrees\app\Http\Middleware\RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->handle(Object(Nyholm\Psr7\ServerRequest))
#17 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#18 D:\xampp\htdocs\webtrees\modules_v4\vesta_research_suggestions\ResearchSuggestionsModule.php(277): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#19 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#20 D:\xampp\htdocs\webtrees\modules_v4\family-tree-home\module.php(77): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#21 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\AbstractModule@anonymous->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#22 D:\xampp\htdocs\webtrees\app\Module\HitCountFooterModule.php(154): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#23 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#24 D:\xampp\htdocs\webtrees\app\Module\CheckForNewVersion.php(122): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#25 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#26 D:\xampp\htdocs\webtrees\app\Http\Middleware\CheckCsrf.php(80): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#27 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#28 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#29 D:\xampp\htdocs\webtrees\app\Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#30 D:\xampp\htdocs\webtrees\app\Http\Middleware\Router.php(163): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#31 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#32 D:\xampp\htdocs\webtrees\app\Http\Middleware\BootModules.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#33 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#34 D:\xampp\htdocs\webtrees\app\Http\Middleware\RegisterGedcomTags.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#35 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#36 D:\xampp\htdocs\webtrees\app\Http\Middleware\LoadRoutes.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#37 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#38 D:\xampp\htdocs\webtrees\app\Http\Middleware\CheckForNewVersion.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#39 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#40 D:\xampp\htdocs\webtrees\app\Http\Middleware\UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#41 D:\xampp\htdocs\webtrees\vendor\illuminate\database\Concerns\ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#42 D:\xampp\htdocs\webtrees\app\Http\Middleware\UseTransaction.php(44): Illuminate\Database\Connection->transaction(Object(Closure), 3)
#43 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#44 D:\xampp\htdocs\webtrees\app\Http\Middleware\DoHousekeeping.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#45 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#46 D:\xampp\htdocs\webtrees\app\Http\Middleware\UseTheme.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#47 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#48 D:\xampp\htdocs\webtrees\app\Http\Middleware\CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#49 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#50 D:\xampp\htdocs\webtrees\app\Http\Middleware\UseLanguage.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#51 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#52 D:\xampp\htdocs\webtrees\app\Http\Middleware\UseSession.php(78): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#53 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#54 D:\xampp\htdocs\webtrees\app\Http\Middleware\UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#55 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#56 D:\xampp\htdocs\webtrees\app\Http\Middleware\UseDatabase.php(122): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#57 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#58 D:\xampp\htdocs\webtrees\app\Http\Middleware\BadBotBlocker.php(308): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#59 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#60 D:\xampp\htdocs\webtrees\app\Http\Middleware\CompressResponse.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#61 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#62 D:\xampp\htdocs\webtrees\app\Http\Middleware\ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#63 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#64 D:\xampp\htdocs\webtrees\vendor\middlewares\client-ip\src\ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#65 D:\xampp\htdocs\webtrees\app\Http\Middleware\ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#66 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#67 D:\xampp\htdocs\webtrees\app\Http\Middleware\HandleExceptions.php(89): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#68 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#69 D:\xampp\htdocs\webtrees\app\Http\Middleware\BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#70 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#71 D:\xampp\htdocs\webtrees\app\Http\Middleware\ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#72 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#73 D:\xampp\htdocs\webtrees\app\Http\Middleware\SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#74 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#75 D:\xampp\htdocs\webtrees\app\Http\Middleware\EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#76 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#77 D:\xampp\htdocs\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#78 D:\xampp\htdocs\webtrees\app\Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest))
#79 D:\xampp\htdocs\webtrees\app\Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array)
#80 D:\xampp\htdocs\webtrees\index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#81 {main}
```

Note:
At first I thought this was a problem of the [Vesta Classic Look & Feel module](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf), which is why I reported the issue [there](https://github.com/vesta-webtrees-2-custom-modules/vesta_classic_laf/issues/144).

But it turns out the problem is not caused by that module. After disabling all modules and enabling them on one by one, it turns out that the problem only occurs when I enable the [Fancy Treeview module](https://justcarmen.nl/modules-webtrees-2/fancy-treeview/).

Can you take a look at how this problem can be solved?

**Comment by TheDutchJewel** [comment]
Even if I disable all modules and enable only Fancy Treeview module, with the same ancestor (×8 grandfather) it still takes 29 seconds to display the individual.

**Comment by JustCarmen** [comment]
I've read your question several times, but I don't understand what you are trying to do. I was not aware of any tagging system (beside simple shared notes), but it is still not clear to me, what your trying to do and which modules you are using for it. Furthermore I don't see what the Fancy treeview module has to do with it. 

The error message starts with: `View file not found: D:\xampp\htdocs\webtrees\modules_v4\jc-fancy-treeview/resources/views/block.phtml`

I guess this file is missing in your installation.

**Comment by TheDutchJewel** [comment]
What I do is click on the father in the family navigator (then his father, then his father etc). The further up the family tree I go, the slower the data is displayed. Normally the data is displayed within 1-2 seconds, but if I enable the `Fancy treeview module`, it suddenly takes much longer (up to, say, 45 seconds if I disable all modules and enable Fancy treeview module only).

By the way, the file `D:\xampp\htdocs\webtrees\modules_v4\jc-fancy-treeview/resources/views/block.phtml` exists. Just to be sure, I replaced module files from the original zip file.

Just tested again. I don't get any error messages now, but this module makes using webtrees unusable due to the huge delay.
If I enable all modules again and disable the `Fancy treeview module`, everything runs smoothly again and the data is displayed within 1-2 seconds.

**Comment by JustCarmen** [comment]
I cannot reproduce this. If I navigate from father to father in a tree of 15 generations, I do not see this behavior. All pages load in a reasonable amount of time.

What settings do you use? Play with the settings to see if it improves page load.
- reduce the maximum number of generations per tab
- set 'show singles' to 'no'.
- set 'check relationship between partners' to 'no'.

I suspect the latter is the culprit.

**Comment by TheDutchJewel** [comment]
Here are my settings:
![Screenshot 2024-05-19 at 08-23-10 Fancy Treeview](https://github.com/JustCarmen/webtrees-fancy-treeview/assets/46184729/0252e83b-3c67-4e39-9c4d-84e1622afd25)

> What settings do you use? Play with the settings to see if it improves page load.
> 
>     • reduce the maximum number of generations per tab
>     • set 'show singles' to 'no'.
>     • set 'check relationship between partners' to 'no'.

The last two options are already disabled.

The problem is in the first option: if I reduce it from 9 to 4 the time runs down from 45 seconds to 6 seconds (at 8 x grandfather)

**Comment by JustCarmen** [comment]
I've set this option to 3 on my own website. One can click the read more tab to see other generations. I guess that a large tree like yours can't handle that much generations at once. It costs to many resources.
