### ISSUE TITLE
Error, webtrees with multiple family trees

### ISSUE THREAD

**Issue by jpretired** [JustCarmen/webtrees-fancy-treeview#83]
webtrees 2.1.8, Fancy Treeview 2.0.0-beta.
After adding a family tree overview to menu and then switching to the other family tree I get an error:

Call to a member function canShow() on null …/modules_v4/jc-fancy-treeview/FancyTreeviewModule.php:424
#0 …/app/Module/ModuleThemeTrait.php(495): JustCarmen\Webtrees\Module\FancyTreeview\FancyTreeviewModule->getMenu()
#1 [internal function]: JustCarmen\Webtrees\Module\JustlightTheme\JustlightTheme::Fisharebest\Webtrees\Module\{closure}()
#2 …/vendor/illuminate/collections/Collection.php(695): array_map()

I guess that the menu item "family tree overview" should only stay in the menu with the family tree in which it was added (sorry for my clumsy English).

**Comment by jpretired** [comment]
I replaced the original FancyTreeviewModule.php with the new one downloaded and now the same error at different line of code:

Call to a member function canShow() on null …/modules_v4/jc-fancy-treeview/FancyTreeviewModule.php:417
#0 …/app/Module/ModuleThemeTrait.php(495): JustCarmen\Webtrees\Module\FancyTreeview\FancyTreeviewModule->getMenu()
#1 [internal function]: Fisharebest\Webtrees\Module\WebtreesTheme::Fisharebest\Webtrees\Module\{closure}()
#2 …/vendor/illuminate/collections/Collection.php(695): array_map()
#3 …/app/Module/ModuleThemeTrait.php(495): Illuminate\Support\Collection->map()
